### ISSUE TITLE
Stalling creating driver again

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness-Ruby#5]
The problem of the script hanging up on this line is happening again:

driver = Selenium::WebDriver.for :firefox, :profile => profile

Last time we thought it was the version of the selenium gem so you put the restriction in the Gemlock file to force it to be at lest 2.43.0, that is what I'm running:

$ grep sele Gemfile
gem "selenium-webdriver", '>=2.43.0'
$ gem list|grep sel
selenium-webdriver (2.43.0)

I also tried with 2.44.0 and that failed as well. Running with strace it seems to be getting stuck trying to make the network connection. curl works fine and the site I'm testing so it is up and returning good data.

Interestingly the site I initially had the failure on is on localhost so assumed the 127.0.0.1 address was normal but I just tested against google and got the stall in the same place with it also trying to do something on 127.0.0.1. I don't know enough about Selenium to know how it works or why it is trying to connect to localhost. The connection seems to be to port 7055, I've checked and have nothing open on that port.

Can you try with strace on your machine and see what you get, I assume you'll get through this step, see what you get after.

futex(0x998634, FUTEX_WAIT_BITSET_PRIVATE, 81, {363846, 694259225}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x9986b0, FUTEX_WAKE_PRIVATE, 1)  = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 10
fcntl(10, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fstat(10, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fstat(10, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fstat(10, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fstat(10, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fcntl(10, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(10, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(10, {sa_family=AF_INET, sin_port=htons(7055), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
select(11, NULL, [10], NULL, {5, 0})    = 1 (out [10], left {4, 999998})
fcntl(10, F_GETFL)                      = 0x802 (flags O_RDWR|O_NONBLOCK)
connect(10, {sa_family=AF_INET, sin_port=htons(7055), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 ECONNREFUSED (Connection refused)
close(10)                               = 0
futex(0x998634, FUTEX_WAIT_BITSET_PRIVATE, 83, {363846, 945992685}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x9986b0, FUTEX_WAKE_PRIVATE, 1)  = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 10

**Comment by ChrisTruncer** [comment]
Here's my full strace out.  It looks to be the same lines at 23071

http://paste.ubuntu.com/8872073/

**Comment by digininja** [comment]
Typical style, finally got round to checking on this and it is working
again. At least we know it wasn't just a one off but something that can be
solved with maybe a few upgrades.

**Comment by ChrisTruncer** [comment]
Ha, seems like this is a case of Murphy's law.  I'm just confused, I don't know what would be causing it.  If you're having this issue, I'm sure someone else out there is.  I'm not sure if this is related to how I'm instantiating a selenium object, or something in the library itself.

**Comment by digininja** [comment]
My guess would be the libraries the gem run against are getting out of
sync. I've done a few updates since initially having the problem and that
may have brought it all back together. If it happens again I'll be a bit
more selective with updates and try to spot anything that might be causing
it.

**Comment by ChrisTruncer** [comment]
ok, sorry about all this.  Appreciate all the help

**Comment by digininja** [comment]
Not your fault.

**Comment by ChrisTruncer** [comment]
Ok, for now, I'll go ahead and close this issue out.  If you run into this again, let me know.
